# src/publisher/config/tasks.yaml

crawler_task:
  description: >
    Search for and collect the latest and most relevant articles on the topic "{topic}" using the Serper API.
    Focus on obtaining complete metadata, including article title, author, publication date, and URL.
    Ensure the articles are trustworthy, recent (preferably within the current year: {current_year}), and from reputable publishers.
  expected_output: >
    A structured list of 5–10 articles with metadata:
    - Title
    - Author
    - Publication Date
    - URL
  agent: crawler_agent

role_generation_task:
  description: >
    Analyze each article and determine a suitable persona or role the simulation agent should adopt when reading and interpreting the content.
    Roles can be "student", "journalist", "policy maker", etc., depending on article context and tone.
  expected_output: >
    A JSON-like structure with:
    - Article title
    - Suggested role
    - Reason for the role
  agent: role_generator

simulation_task:
  description: >
    For each article, simulate how a user with the assigned role would interpret the content. Generate a realistic prompt and a 2–3 sentence interpretation.
  expected_output: >
    A JSON-like structure with:
    - Article title
    - Assigned role
    - Simulated prompt
    - AI interpretation (2–3 sentences)
    - Citation (author, year, and URL)
  agent: simulation_agent

summarization_task:
  description: >
    Using the AI interpretations, simulated prompts, and article metadata, generate polished, markdown-formatted summaries for publication.
    Each summary should not only capture the main points of the article but also include a realistic answer to the simulated prompt, derived from the article’s insights and role-specific interpretation.
  expected_output: >
    A markdown document where each article has the following structure:

    # Article Summary for "<Article Title>"  
    **Citation**: <Author>, <Year>. <Title>. Retrieved from <URL>  
    **Role**: <Assigned Role>  
    **Simulated Prompt**: <Prompt used for interpretation>  
    **AI Interpretation**: <2–3 sentence summary>  
    **Prompt Answer**: <Direct answer to the simulated prompt. 2 paragraphs>
  agent: summarization_agent
  output_file: summaries.md
