# src/publisher/config/tasks.yaml

crawler_task:
  description: >
    Use the Serper API to search and collect 5–10 recent articles mentioning "{topic}" or its competitors.
    Ensure results are from credible media outlets and dated within the current year: {current_year}.
  expected_output: >
    A structured list of articles with:
    - Title
    - Author
    - Publication Date
    - URL
  agent: crawler_agent

role_generation_task:
  description: >
    Analyze each article’s content and tone to assign a relevant perspective (consumer, journalist, investor, etc.) for simulation.
  expected_output: >
    JSON-like structure with:
    - Article title
    - Suggested role
    - Reason for selection
  agent: role_generator

simulation_task:
  description: >
    For each article, simulate how a user with the assigned role would interpret the content.
    Generate a realistic prompt, a 2–3 sentence interpretation, and assess sentiment from the role’s perspective.
  expected_output: >
    A JSON-like structure with:
    - Article title
    - Assigned role
    - Simulated prompt
    - AI interpretation (2–3 sentences)
    - Sentiment (positive, negative, neutral)
    - Citation (author, year, and URL)
  agent: simulation_agent

summarization_task:
  description: >
    Create PR-ready markdown summaries per article using the stakeholder’s interpretation and article metadata.
    Include realistic responses to simulated prompts and note any PR risks or reputation signals.
  expected_output: >
    Markdown summary for each article:
    
    # Brand Reputation Summary: "<Article Title>"
    **Citation**: <Author>, <Year>. <Title>. Retrieved from <URL>  
    **Role**: <Assigned Role>  
    **Simulated Prompt**: <Prompt>  
    **Stakeholder Interpretation**: <2–3 sentence summary>  
    **PR Insight**: <300 words. Describe the likely public/press/investor reaction and any risk or opportunity for the brand.>
    **Sentiment**: <positive | neutral | negative>  
    **PR Keywords Detected**: [<list of keywords>]
  agent: summarization_agent
  output_file: summaries.md
