research_task:
  description: >
    Analyze content extracted from the URL: {url}, with special focus on the marketing topic: "{topic}".
    Your objectives are to:
      - Summarize main ideas and content structure.
      - Classify the domain/category of the content (e.g., tech, lifestyle).
      - Extract actionable insights for targeting.
      - Relate all findings to the context of the provided topic.
  expected_output: >
    A plain-text report with:
      1. Summary (3–5 sentences)
      2. Domain classification with reason
      3. 5–7 bullet points of insights
      4. Explanation of relevance to the topic "{topic}", especially for ad and audience strategy
  agent: researcher

audience_taxonomy_task:
  description: >
    From the research findings, suggest only valid audience taxonomy nodes from the official dataset.
    Do not invent or extrapolate any nodes.
  expected_output: >
    A list of audience taxonomy nodes, each including:
      - Taxonomy Type
      - Unique ID
      - Condensed Name
      - Tiers 1 to 6
      - Extension Notes (if any)
      - Explanation for each node's relevance
  agent: audience_taxonomy_agent

content_taxonomy_task:
  description: >
    Using the research insights, classify the content using only valid nodes from the content taxonomy dataset.
  expected_output: >
    A prioritized list of valid content taxonomy nodes including:
      - Taxonomy Type
      - Unique ID
      - Name
      - Tiers 1 to 4
      - Extension (if any)
      - Justification for selection
  agent: content_taxonomy_agent

adproduct_taxonomy_task:
  description: >
    Suggest ad product taxonomy nodes that match the research insights, using only entries from the official taxonomy.
  expected_output: >
    A list of ad product taxonomy nodes with:
      - Taxonomy Type
      - Unique ID
      - Name
      - Tiers 1 to 3
      - Extension Notes (if any)
      - Explanation for how each aligns with content or target audience
  agent: adproduct_taxonomy_agent

scoring_task:
  description: >
    Evaluate taxonomy nodes (Content, Audience, Ad Product) for contextual accuracy.
    Assign confidence scores (0 to 1) and provide detailed justifications.
  expected_output: >
    A plain-text report containing:
      1. A table with columns:
         - Taxonomy Type
         - Unique ID
         - Name
         - Confidence Score (0–1)
         - Evaluation Notes
      2. Average confidence score summary
      3. Processing metadata (runtime, timestamp)
  agent: scoring_agent

show_creatives_task:
  description: >
    Based on taxonomy matches with confidence score ≥ 0.8, suggest ad creative ideas grouped by taxonomy type.
  expected_output: >
    A markdown section listing ad creative ideas grouped by:
      - Audience
      - Content
      - Ad Product
    Include 1–2 examples per group with specific, actionable ad strategies.
  agent: creative_agent
